CREATE TABLE t_e_utilisateur_utl (
    utl_id integer GENERATED BY DEFAULT AS IDENTITY,
    utl_pseudo character varying(25) NOT NULL,
    utl_nom character varying(50) NULL,
    utl_prenom character varying(50) NULL,
    utl_mail character varying(100) NOT NULL,
    utl_motdepasse character varying(130) NOT NULL,
    utl_description character varying(500) NULL,
    CONSTRAINT pk_utl PRIMARY KEY (utl_id)
);

CREATE TABLE t_e_post_pos (
    pos_id integer GENERATED BY DEFAULT AS IDENTITY,
    pos_idutilisateur integer NOT NULL,
    pos_surid integer NULL,
    pos_message character varying(280) NULL,
    pos_datecreation date NULL DEFAULT (CURRENT_DATE),
    CONSTRAINT pk_pos PRIMARY KEY (pos_id),
    CONSTRAINT fk_pos_pos FOREIGN KEY (pos_surid) REFERENCES t_e_post_pos (pos_id) ON DELETE RESTRICT,
    CONSTRAINT fk_pos_utl FOREIGN KEY (pos_idutilisateur) REFERENCES t_e_utilisateur_utl (utl_id) ON DELETE CASCADE
);

CREATE TABLE t_j_favs_fav (
    fav_idutilsateur integer NOT NULL,
    fav_idpost integer NOT NULL,
    CONSTRAINT pk_fav PRIMARY KEY (fav_idutilsateur, fav_idpost),
    CONSTRAINT fk_fav_pos FOREIGN KEY (fav_idpost) REFERENCES t_e_post_pos (pos_id) ON DELETE RESTRICT,
    CONSTRAINT fk_fav_utl FOREIGN KEY (fav_idutilsateur) REFERENCES t_e_utilisateur_utl (utl_id) ON DELETE RESTRICT
);

CREATE TABLE t_j_retweet_ret (
    ret_idutilsateur integer NOT NULL,
    ret_idpost integer NOT NULL,
    CONSTRAINT pk_ret PRIMARY KEY (ret_idutilsateur, ret_idpost),
    CONSTRAINT fk_ret_pos FOREIGN KEY (ret_idpost) REFERENCES t_e_post_pos (pos_id) ON DELETE RESTRICT,
    CONSTRAINT fk_ret_utl FOREIGN KEY (ret_idutilsateur) REFERENCES t_e_utilisateur_utl (utl_id) ON DELETE RESTRICT
);

CREATE INDEX "IX_t_e_post_pos_pos_idutilisateur" ON t_e_post_pos (pos_idutilisateur);

CREATE INDEX "IX_t_e_post_pos_pos_surid" ON t_e_post_pos (pos_surid);

CREATE UNIQUE INDEX uq_utl_mail ON t_e_utilisateur_utl (utl_mail);

CREATE UNIQUE INDEX uq_utl_pseudo ON t_e_utilisateur_utl (utl_pseudo);

CREATE INDEX "IX_t_j_favs_fav_fav_idpost" ON t_j_favs_fav (fav_idpost);

CREATE INDEX "IX_t_j_retweet_ret_ret_idpost" ON t_j_retweet_ret (ret_idpost);

ALTER TABLE t_e_post_pos ADD pos_url varchar(150) NULL;

insert into t_e_utilisateur_utl (utl_pseudo, utl_nom, utl_prenom, utl_mail, utl_motdepasse, utl_description)
values ('leichtmj', 'lei','jim','jim@gmail.com','root','Génie du mal, mais génie quand même.');
insert into t_e_utilisateur_utl (utl_pseudo, utl_nom, utl_prenom, utl_mail, utl_motdepasse, utl_description)
values ('genoncej', 'genon','jane','jane@gmail.com','root','Fear me. For one fell swoop, the ice of my blade will grant you an eternal slumber.');
insert into t_e_utilisateur_utl (utl_pseudo, utl_nom, utl_prenom, utl_mail, utl_motdepasse, utl_description)
values ('IUT', 'Savoie','MontBlanc','savoieMB@gmail.com','iutTweet23!','Just an account to try Cerulean Warbler out.');


insert into t_e_post_pos (pos_idutilisateur, pos_surid, pos_message, pos_datecreation, pos_url) 
values (1,null, 'Premier warble, début de la gloire.', '2023-02-17', 'https://tenor.com/fr/view/css-king-gif-24638596.gif');
insert into t_e_post_pos (pos_idutilisateur, pos_surid, pos_message, pos_datecreation) 
values (1,null, 'Deuxième warble, suite de la gloire.', '2023-03-02');
insert into t_e_post_pos (pos_idutilisateur, pos_surid, pos_message, pos_datecreation, pos_url) 
values (2,null, 'QUASOOOOOOOOOOOOOOOOOOOO', '2022-12-25', 'https://i.imgur.com/PzbhX4o.png');
insert into t_e_post_pos (pos_idutilisateur, pos_surid, pos_message, pos_datecreation, pos_url) 
values (1,null, 'Question.', '2023-01-20', 'https://www.hubspot.com/hubfs/questio.png');
insert into t_e_post_pos (pos_idutilisateur, pos_surid, pos_message, pos_datecreation) 
values (1,4, 'Réponse.', '2023-01-21');
insert into t_e_post_pos (pos_idutilisateur, pos_surid, pos_message, pos_datecreation) 
values (3,null, 'Hello, this is the beginnning of my journey!', '2023-04-01');